version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    environment:
      PORT: 8000
    volumes:
      - ./api:/app
    expose:
      - 8000

  www:
    build:
      context: ./www
      dockerfile: Dockerfile.development
    volumes:
      - ./www/src:/app
    links:
      - api
    ports:
      - 8080:80
