version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.production
    environment:
      PORT: 8000
    expos:
      - 8000

  www:
    build:
      context: ./www
      dockerfile: Dockerfile.production
    links:
      - api
    ports:
      - 65004:80
