service: presidents-api

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-prune-plugin

package:
  exclude:
    - node_modules/serverless-prune-plugin/**

functions:
  presidents-api:
    name: presidents-api
    description: US Presidents API
    handler: lambda.main
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{filter+}
          method: get
          cors: true

custom:
  prune:
    automatic: true
    number: 1
