version: 2
jobs:
  build:
    docker:
      - image: node:6.10
    steps:
      - checkout
      - run:
          name: update npm
          command: npm install -g npm@6
      - run:
          name: deal with weird strip-ansi issue
          command: cp -r /usr/local/lib/node_modules/npm/node_modules/string-width/node_modules/strip-ansi /usr/local/lib/node_modules/npm/node_modules/
      - run:
          name: install dependencies
          command: npm ci --only=production
      - run:
          name: install serverless
          command: npm i -g serverless
      - run:
          name: install serverless plugins
          command: npm install serverless-prune-plugin
      - run:
          name: deploy
          command: serverless deploy --stage production --region $SERVERLESS_DEPLOY_REGION
